---

- name: verify
  hosts: all
  tasks:

    - name: check package installation
      ansible.builtin.package:
        name: systemd
        state: present
      check_mode: yes
      register: __systemd_resolved_installed

    - name: debug package installation
      ansible.builtin.debug:
        var: __systemd_resolved_installed

    - name: assert on package installation
      ansible.builtin.assert:
        that:
          - not __systemd_resolved_installed.failed
          - not __systemd_resolved_installed.changed
          - __systemd_resolved_installed.msg == 'package(s) already installed'
        success_msg: 'package is installed'

    - name: check service
      ansible.builtin.service:
        name: systemd-resolved
        enabled: yes
        state: started
      check_mode: yes
      register: __systemd_resolved_service

    - name: debug service
      ansible.builtin.debug:
        var: __systemd_resolved_service

    - name: assert on service
      ansible.builtin.assert:
        that:
          - not __systemd_resolved_service.failed
          - not __systemd_resolved_service.changed
          - __systemd_resolved_service.state == 'started'
          - __systemd_resolved_service.enabled
        success_msg: 'service is both enabled and started'

    - name: check if resolvectl status works
      ansible.builtin.command: resolvectl status
      changed_when: no

    - name: check if systemd-resolve can resolve
      ansible.builtin.command: systemd-resolve archlinux.org
      changed_when: no

...
