---

name: ansible-lint

on:
  pull_request:
  push:
    branches:
      - main
      - wip/next

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ansible/ansible-lint-action@v6

...
