---

name: ansible

on:
  pull_request:
  push:
    branches:
      - main
      - wip/next

jobs:

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint-action@v6

  molecule:
    needs:
      - ansible-lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - archlinux
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip3 install ansible molecule molecule-plugins[docker] docker
      - run: molecule test -p ${{ matrix.distro }}
        env:
          PY_COLORS: '1'

...
